"""gameinstances.user

Revision ID: 1f1557e8bc96
Revises: a8d7c11c7660
Create Date: 2023-11-27 13:24:02.845607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1557e8bc96'
down_revision = 'a8d7c11c7660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gameinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_gameinstances_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gameinstances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gameinstances_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
