"""add totalscore

Revision ID: 458599f102a1
Revises: afae77319914
Create Date: 2023-08-24 23:36:39.798297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458599f102a1'
down_revision = 'afae77319914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('total_score')

    # ### end Alembic commands ###
