"""tables and reltables

Revision ID: 7916211ee90d
Revises: 31a7a4f07948
Create Date: 2023-08-15 12:33:49.556791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7916211ee90d'
down_revision = '31a7a4f07948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_attendances_player_id_players')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_attendances_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendances'))
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_instance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_instance_id'], ['gameinstances.id'], name=op.f('fk_scores_game_instance_id_gameinstances')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_scores_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores'))
    )
    with op.batch_alter_table('gameinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_gameinstances_session_id_sessions'), 'sessions', ['session_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_gameinstances_game_id_games'), 'games', ['game_id'], ['id'])

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('publisher')
        batch_op.drop_column('title')

    with op.batch_alter_table('gameinstances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gameinstances_game_id_games'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_gameinstances_session_id_sessions'), type_='foreignkey')
        batch_op.drop_column('game_id')
        batch_op.drop_column('session_id')

    op.drop_table('scores')
    op.drop_table('attendances')
    op.drop_table('sessions')
    op.drop_table('players')
    # ### end Alembic commands ###
