"""more janky columns for players

Revision ID: a8d7c11c7660
Revises: 458599f102a1
Create Date: 2023-08-25 00:01:38.854214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d7c11c7660'
down_revision = '458599f102a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_placement', sa.Numeric(precision=2, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('average_placement')
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
